# -*- coding: utf-8 -*-
"""
knowledge.py — the curated philosophical knowledge base.

Each ELEMENT is one atomic, sentence-level idea (a concept / claim / rule / method)
distilled from the primary sources downloaded in stage 1. Every element is tagged with:
  theme  : one of THEMES   (the top-level taxonomy axis)
  stance : its position on that axis (drives equivalence vs. contradiction detection)
  keywords / quote : feed the automatic TF-IDF similarity in stage 3
  thinker -> THINKER[...] -> civ / school / link to the original text online

The stage-3 relation engine is automatic (TF-IDF cosine + lexical antonym cues); the
`stance` labels + OPPOSITIONS map encode the documented scholarly debates so that
agreement (equivalence) and disagreement (contradiction) can be separated.
"""

# --------------------------------------------------------------------------- themes
THEMES = {
    "arche":      ("Origin & Substance of the Cosmos", "What is the first principle (archē) from which all things come?", "#c9a24b"),
    "change":     ("Change, Permanence & Becoming",    "Is reality flux, or changeless being?",                          "#5fb0c9"),
    "reality":    ("What Is Real — Matter, Mind & Form","Is the ground of reality matter, mind, or eternal Form?",        "#9b87d4"),
    "self":       ("The Self & the Soul",              "Is there an enduring soul — and does it survive death?",         "#d98cc0"),
    "knowledge":  ("Knowledge, Truth & Skepticism",    "What can we know, and how — reason, sense, or not at all?",      "#69b06b"),
    "divine":     ("The Divine — Gods, the One & Dualism","One god, many, two principles, or none?",                     "#e0a23c"),
    "nature":     ("Human Nature",                     "Are humans born good, bad, blank, or self-interested?",         "#e8902e"),
    "good":       ("The Good Life & Virtue",           "What is the highest good and how should one live?",             "#d8b34a"),
    "ahimsa":     ("Compassion, Non-violence & the Golden Rule","How should we treat others?",                          "#5bbf9b"),
    "order":      ("Political Order — Virtue, Law & Non-action","How should society be governed?",                       "#cf5b4e"),
    "justice":    ("Cosmic Justice & Moral Law",       "Is there an objective moral order woven into the cosmos?",      "#c98a5f"),
    "liberation": ("Suffering, Death & Liberation",    "What is the answer to suffering and mortality?",                "#7d9bd4"),
    "fate":       ("Fate & Freedom",                   "Is the human will free, or is all determined?",                 "#b07cc9"),
}

# Stances that CONTRADICT one another within a theme (order-independent pairs).
OPPOSITIONS = {
    "change":  [("flux", "permanence"), ("unity-of-opposites", "permanence")],
    "reality": [("materialist", "idealist"), ("materialist", "mind-orders"),
                ("materialist", "form-realism"), ("dualist", "idealist")],
    "self":    [("eternal-self", "no-self"), ("eternal-self", "mortal-material"),
                ("transmigration", "no-self"), ("transmigration", "mortal-material")],
    "nature":  [("good", "bad"), ("good", "self-interested"), ("good", "malleable-toward-bad")],
    "divine":  [("monotheism", "agnostic-atheist"), ("monotheism", "ethical-dualism"),
                ("monotheism", "naturalist"), ("monotheism", "deist-indifferent")],
    "knowledge": [("rationalism", "empiricism-only"), ("revealed-wisdom", "skeptic"),
                  ("rationalism", "skeptic")],
    "good":    [("hedonist", "virtue-only"), ("hedonist", "asceticism")],
    "order":   [("rule-by-virtue", "rule-by-law"), ("rule-by-law", "non-action"),
                ("rule-by-virtue", "non-action")],
    "fate":    [("free-will", "determinism")],
    "liberation": [("release-rebirth", "accept-annihilation")],
}

# Explicit cross-theme contradictions (by element id) — the famous debates that
# straddle two axes (e.g. universal love vs. rule by punishment).
CROSS_CONTRA = [
    ("mozi.anti-war", "sunzi.strategy"),
    ("mozi.universal-love", "hanfeizi.law"),
    ("mozi.universal-love", "shangyang.law"),
    ("mahavira.ahimsa", "sunzi.strategy"),
    ("buddha.anatta", "upanishads.atman"),
    ("carvaka.empiricism", "parmenides.reason"),
    ("gosala.determinism", "zoroaster.free-choice"),
    ("epicurus.death", "upanishads.moksha"),
    ("epicurus.pleasure", "zenocitium.virtue"),
]

# --------------------------------------------------------------------------- thinkers
# thinker -> (native name, civilization, school, link to original text online)
H = "https://history.hanover.edu/texts/presoc/"
CT = "https://ctext.org/"
ST = "https://sacred-texts.com/"
SF = "https://www.sefaria.org/"
WS = "https://en.wikisource.org/wiki/"
PER = "https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:"

THINKER = {
    # Greece
    "Thales":        ("Θαλῆς", "Greece", "Milesian", H + "thales.html"),
    "Anaximander":   ("Ἀναξίμανδρος", "Greece", "Milesian", H + "anaximan.html"),
    "Anaximenes":    ("Ἀναξιμένης", "Greece", "Milesian", H + "anaximen.html"),
    "Pythagoras":    ("Πυθαγόρας", "Greece", "Pythagorean", H + "pythagor.html"),
    "Xenophanes":    ("Ξενοφάνης", "Greece", "Eleatic", H + "Xenophan.html"),
    "Heraclitus":    ("Ἡράκλειτος", "Greece", "Ionian", WS + "Fragments_of_Heraclitus"),
    "Parmenides":    ("Παρμενίδης", "Greece", "Eleatic", H + "parmends.html"),
    "Zeno of Elea":  ("Ζήνων ὁ Ἐλεάτης", "Greece", "Eleatic", H + "zeno.html"),
    "Empedocles":    ("Ἐμπεδοκλῆς", "Greece", "Pluralist", H + "emp.html"),
    "Anaxagoras":    ("Ἀναξαγόρας", "Greece", "Pluralist", H + "anaxagor.html"),
    "Democritus":    ("Δημόκριτος", "Greece", "Atomist", "https://archive.org/details/firstphilosopher00fairiala"),
    "Protagoras":    ("Πρωταγόρας", "Greece", "Sophist", "https://www.perseus.tufts.edu/hopper/collection?collection=Perseus:corpus:perseus,author,Plato"),
    "Gorgias":       ("Γοργίας", "Greece", "Sophist", "https://www.perseus.tufts.edu/hopper/collection?collection=Perseus:corpus:perseus,author,Plato"),
    "Socrates":      ("Σωκράτης", "Greece", "Classical", "https://classics.mit.edu/Plato/apology.html"),
    "Plato":         ("Πλάτων", "Greece", "Classical", PER + "1999.01.0168"),
    "Aristotle":     ("Ἀριστοτέλης", "Greece", "Classical", PER + "1999.01.0053"),
    "Diogenes":      ("Διογένης", "Greece", "Cynic", WS + "Lives_of_the_Eminent_Philosophers/Book_VI"),
    "Epicurus":      ("Ἐπίκουρος", "Greece", "Hellenistic", WS + "Lives_of_the_Eminent_Philosophers/Book_X"),
    "Zeno of Citium":("Ζήνων ὁ Κιτιεύς", "Greece", "Hellenistic", WS + "Lives_of_the_Eminent_Philosophers/Book_VII"),
    # China
    "Confucius":     ("孔子", "China", "Confucian", CT + "analects"),
    "Mencius":       ("孟子", "China", "Confucian", CT + "mengzi"),
    "Xunzi":         ("荀子", "China", "Confucian", CT + "xunzi"),
    "Laozi":         ("老子", "China", "Daoist", CT + "dao-de-jing"),
    "Zhuangzi":      ("莊子", "China", "Daoist", CT + "zhuangzi"),
    "Mozi":          ("墨子", "China", "Mohist", CT + "mozi"),
    "Shang Yang":    ("商鞅", "China", "Legalist", CT + "shang-jun-shu"),
    "Han Feizi":     ("韓非子", "China", "Legalist", CT + "han-feizi"),
    "Sun Tzu":       ("孫子", "China", "Strategist", CT + "art-of-war"),
    "Gongsun Long":  ("公孫龍", "China", "School of Names", CT + "gongsunlongzi"),
    # India
    "Vedas":         ("वेद", "India", "Vedic", ST + "hin/rigveda/index.htm"),
    "Upanishads":    ("उपनिषद्", "India", "Vedānta", ST + "hin/sbe01/index.htm"),
    "Mahavira":      ("महावीर", "India", "Jain", ST + "jai/index.htm"),
    "Buddha":        ("बुद्ध", "India", "Buddhist", ST + "bud/sbe10/index.htm"),
    "Makkhali Gosala":("मक्खलि गोसाल", "India", "Ājīvika", ST + "bud/index.htm"),
    "Carvaka":       ("चार्वाक", "India", "Cārvāka", ST + "hin/index.htm"),
    "Kapila":        ("कपिल", "India", "Sāṃkhya", ST + "hin/index.htm"),
    "Panini":        ("पाणिनि", "India", "Grammarian", "https://archive.org/details/ashtadhyayitrans06paniuoft"),
    # Persia
    "Zoroaster":     ("زرتشت", "Persia", "Zoroastrian", "https://www.avesta.org/gathas.htm"),
    # Hebrew
    "Proverbs":      ("מִשְׁלֵי", "Israel", "Wisdom", SF + "Proverbs"),
    "Ecclesiastes":  ("קֹהֶלֶת", "Israel", "Wisdom", SF + "Ecclesiastes"),
    "Job":           ("אִיּוֹב", "Israel", "Wisdom", SF + "Job"),
    "Torah":         ("תּוֹרָה", "Israel", "Law", SF + "Genesis"),
    "Prophets":      ("נְבִיאִים", "Israel", "Prophetic", SF + "Amos"),
    # Egypt
    "Ptahhotep":     ("ptḥ-ḥtp", "Egypt", "Sebayt", "https://www.gutenberg.org/files/30508/30508-h/30508-h.htm"),
    "Amenemope":     ("jmn-m-jpt", "Egypt", "Sebayt", ST + "egy/index.htm"),
    "Akhenaten":     ("ꜣḫ-n-jtn", "Egypt", "Atenist", "https://www.historyskills.com/classroom/ancient-history/hymn-to-the-aten/"),
    "Dispute with the Ba": ("Papyrus Berlin 3024", "Egypt", "Sebayt", ST + "egy/index.htm"),
    "Book of the Dead": ("rꜣ nw prt m hrw", "Egypt", "Funerary", ST + "egy/ebod/index.htm"),
    # Mesopotamia
    "Instructions of Shuruppak": ("𒋗𒆳𒆠", "Mesopotamia", "Wisdom", "https://etcsl.orinst.ox.ac.uk/section5/tr561.htm"),
    "Epic of Gilgamesh": ("𒄑𒂅𒈠", "Mesopotamia", "Epic", ST + "ane/eog/index.htm"),
    "Babylonian Theodicy": ("ludlul bēl nēmeqi", "Mesopotamia", "Wisdom", ST + "ane/index.htm"),
    "Dialogue of Pessimism": ("arad mitanguranni", "Mesopotamia", "Wisdom", ST + "ane/index.htm"),
    "Hammurabi":     ("𒄩𒄠𒈬𒊏𒁉", "Mesopotamia", "Law", "https://avalon.law.yale.edu/ancient/hamframe.asp"),
    "Enuma Elish":   ("𒂊𒉡𒈠𒂊𒇺", "Mesopotamia", "Cosmogony", ST + "ane/enuma.htm"),
}

# --------------------------------------------------------------------------- elements
# (id, thinker, type, theme, stance, text, keywords, quote)
def E(_id, thinker, typ, theme, stance, text, keywords, quote=""):
    return {"id": _id, "thinker": thinker, "type": typ, "theme": theme,
            "stance": stance, "text": text, "keywords": keywords, "quote": quote}

ELEMENTS = [
    # ---------------- GREECE ----------------
    E("thales.water", "Thales", "claim", "arche", "monist-material",
      "Water is the fundamental principle (archē) out of which all things arise.",
      "water arche origin principle first substance moisture"),
    E("thales.hylozoism", "Thales", "concept", "divine", "immanent",
      "All things are full of gods; even magnets have soul, for the world is alive.",
      "gods soul alive magnet hylozoism divine immanent"),
    E("anaximander.apeiron", "Anaximander", "claim", "arche", "monist-abstract",
      "The source of all things is the apeiron — the boundless, undefined and eternal.",
      "apeiron boundless infinite indefinite origin eternal"),
    E("anaximander.recompense", "Anaximander", "concept", "justice", "cosmic-order",
      "Things pay penalty and recompense to one another for injustice according to the order of time.",
      "justice recompense penalty opposites order time cosmic balance"),
    E("anaximander.evolution", "Anaximander", "claim", "reality", "materialist",
      "Living creatures arose from moisture; humans first developed inside other animals.",
      "life origin animals evolution moisture natural"),
    E("anaximenes.air", "Anaximenes", "claim", "arche", "monist-material",
      "Air is the primary substance; by condensation and rarefaction it becomes all things.",
      "air breath condensation rarefaction substance pneuma"),
    E("pythagoras.number", "Pythagoras", "claim", "reality", "form-realism",
      "Number is the essence and structure of all reality; the cosmos is ordered by ratio.",
      "number mathematics harmony ratio form structure cosmos"),
    E("pythagoras.soul", "Pythagoras", "claim", "self", "transmigration",
      "The soul is immortal and transmigrates through a succession of bodies.",
      "soul immortal transmigration reincarnation rebirth metempsychosis"),
    E("pythagoras.harmony", "Pythagoras", "concept", "good", "harmony",
      "Purify and tune the soul by harmony, as musical ratios tune the lyre.",
      "harmony music purification order soul tuning"),
    E("xenophanes.onegod", "Xenophanes", "claim", "divine", "monotheism",
      "Mortals imagine gods in their own image; in truth there is one greatest god unlike mortals.",
      "anthropomorphism one god critique images oxen unity divine"),
    E("xenophanes.limits", "Xenophanes", "claim", "knowledge", "skeptic",
      "No man has seen or will know the certain truth; over all there is only seeming.",
      "uncertain truth opinion seeming limits fallible knowledge"),
    E("heraclitus.flux", "Heraclitus", "concept", "change", "flux",
      "Everything flows; you cannot step twice into the same river.",
      "flux change river becoming flow impermanence motion", "πάντα ῥεῖ"),
    E("heraclitus.logos", "Heraclitus", "concept", "knowledge", "logos-order",
      "All things come to pass according to the Logos — the one universal reason and law.",
      "logos reason law order word universal intelligible"),
    E("heraclitus.opposites", "Heraclitus", "concept", "change", "unity-of-opposites",
      "Opposites are one; strife is justice, and the world is an ever-living fire.",
      "opposites strife war fire tension unity harmony"),
    E("parmenides.being", "Parmenides", "claim", "change", "permanence",
      "Being is and cannot not-be; what truly is, is one, ungenerated and changeless.",
      "being one changeless eternal unchanging motionless whole"),
    E("parmenides.reason", "Parmenides", "method", "knowledge", "rationalism",
      "Follow reason, not the deceiving senses; change and plurality are mere illusion.",
      "reason senses illusion logic truth way of truth deception"),
    E("zeno.paradox", "Zeno of Elea", "claim", "change", "permanence",
      "Motion is impossible — Achilles can never overtake the tortoise; plurality is contradictory.",
      "paradox motion achilles tortoise infinite divisibility impossible"),
    E("empedocles.roots", "Empedocles", "claim", "arche", "pluralist",
      "All things arise from four roots — earth, water, air, fire — joined by Love and split by Strife.",
      "elements four roots earth water air fire love strife mixture"),
    E("empedocles.transmigration", "Empedocles", "claim", "self", "transmigration",
      "The fallen spirit is reborn through plants, beasts and men; abstain from bloodshed.",
      "transmigration rebirth purification daimon soul reincarnation"),
    E("anaxagoras.nous", "Anaxagoras", "claim", "reality", "mind-orders",
      "Mind (Nous) sets all things in order; in everything there is a portion of everything.",
      "nous mind intelligence order seeds portion arrangement"),
    E("democritus.atoms", "Democritus", "claim", "reality", "materialist",
      "Nothing exists but atoms and void; all change is only atoms combining and separating.",
      "atoms void matter particles mechanism nothing-but materialism indivisible"),
    E("democritus.convention", "Democritus", "claim", "knowledge", "empiricism-only",
      "Sweet and bitter exist by convention; in reality there are only atoms and void.",
      "convention qualities perception sweet bitter senses appearance"),
    E("democritus.euthymia", "Democritus", "concept", "good", "tranquility",
      "The goal of life is cheerfulness (euthymia) — a calm, contented and fearless mind.",
      "cheerfulness euthymia tranquility contentment calm fearless"),
    E("protagoras.measure", "Protagoras", "claim", "knowledge", "skeptic",
      "Man is the measure of all things — truth is relative to the perceiver.",
      "measure man relative subjective relativism perception truth", "πάντων χρημάτων μέτρον ἄνθρωπος"),
    E("protagoras.agnostic", "Protagoras", "claim", "divine", "agnostic-atheist",
      "Concerning the gods I cannot know whether they exist or not, nor what they are like.",
      "gods agnostic unknown uncertain existence"),
    E("gorgias.nihilism", "Gorgias", "claim", "knowledge", "skeptic",
      "Nothing exists; if it did it could not be known; if known it could not be communicated.",
      "nothing nonexistence unknowable incommunicable nihilism rhetoric"),
    E("socrates.virtue", "Socrates", "claim", "good", "virtue-as-knowledge",
      "Virtue is knowledge; no one does wrong willingly, but only through ignorance.",
      "virtue knowledge ignorance wrongdoing willing good"),
    E("socrates.ignorance", "Socrates", "method", "knowledge", "critical-inquiry",
      "The only true wisdom is in knowing that you know nothing.",
      "ignorance wisdom questioning elenchus know nothing inquiry humility"),
    E("socrates.examined", "Socrates", "claim", "good", "self-examination",
      "The unexamined life is not worth living.",
      "examined life self-knowledge soul care reflection"),
    E("plato.forms", "Plato", "concept", "reality", "idealist",
      "Beyond the changing world of the senses lies the eternal, perfect realm of Forms.",
      "forms ideas ideal eternal perfect cave appearance reality"),
    E("plato.soul", "Plato", "claim", "self", "transmigration",
      "The soul is immortal and threefold — reason, spirit and appetite — and is reborn.",
      "soul immortal tripartite reason spirit appetite rebirth"),
    E("plato.philosopherking", "Plato", "claim", "order", "rule-by-virtue",
      "The just city must be ruled by philosopher-kings who know the Good.",
      "philosopher king guardians justice city rule wisdom good"),
    E("plato.justice", "Plato", "concept", "good", "harmony",
      "Justice is harmony — each part of the soul and the city doing its proper work.",
      "justice harmony soul city balance parts order virtue"),
    E("aristotle.mean", "Aristotle", "rule", "good", "virtue-mean",
      "Virtue is a mean between extremes, formed by habit; the end of life is eudaimonia (flourishing).",
      "mean virtue moderation habit eudaimonia flourishing extremes balance"),
    E("aristotle.hylomorphism", "Aristotle", "concept", "reality", "form-realism",
      "Every substance is a union of form and matter; the soul is the form of a living body.",
      "form matter substance hylomorphism actuality soul potentiality"),
    E("aristotle.causes", "Aristotle", "method", "knowledge", "rationalism",
      "To know a thing is to know its four causes — material, formal, efficient and final.",
      "four causes material formal efficient final teleology purpose explanation"),
    E("aristotle.mover", "Aristotle", "claim", "divine", "first-cause",
      "All motion traces back to an Unmoved Mover — pure actuality, thought thinking itself.",
      "unmoved mover first cause actuality god prime motion"),
    E("aristotle.political", "Aristotle", "claim", "order", "rule-by-virtue",
      "Man is by nature a political animal; the polis exists for the sake of the good life.",
      "political animal polis city constitution citizen community good life"),
    E("diogenes.asceticism", "Diogenes", "claim", "good", "asceticism",
      "Virtue is the only good; live self-sufficiently, shamelessly free of convention and desire.",
      "virtue self-sufficiency asceticism convention nature autarky simplicity cynic"),
    E("diogenes.cosmopolitan", "Diogenes", "claim", "order", "non-action",
      "Asked where he came from, he said: 'I am a citizen of the world' (cosmopolites).",
      "cosmopolitan world citizen convention freedom borderless"),
    E("epicurus.pleasure", "Epicurus", "claim", "good", "hedonist",
      "Pleasure — freedom from bodily pain and mental disturbance (ataraxia) — is the goal of life.",
      "pleasure ataraxia pain desire happiness tranquility hedonism"),
    E("epicurus.death", "Epicurus", "claim", "liberation", "accept-annihilation",
      "Death is nothing to us: when we exist death is not, and when death is, we are not.",
      "death fear nothing mortality annihilation atoms end"),
    E("epicurus.atoms", "Epicurus", "claim", "reality", "materialist",
      "The universe is only atoms and void, infinite and ungoverned by any god.",
      "atoms void infinite swerve materialism nature mechanism"),
    E("epicurus.gods", "Epicurus", "claim", "divine", "deist-indifferent",
      "The gods exist but are blessed and immortal, taking no concern with human affairs.",
      "gods indifferent blessed no providence detached"),
    E("zenocitium.virtue", "Zeno of Citium", "claim", "good", "virtue-only",
      "Live in agreement with nature and reason; virtue alone is good, all externals indifferent.",
      "nature reason virtue indifferents stoic agreement good externals"),
    E("zenocitium.fate", "Zeno of Citium", "concept", "fate", "determinism",
      "The cosmos is governed by divine reason (logos); accept fate with equanimity.",
      "fate logos providence nature acceptance determinism reason equanimity"),

    # ---------------- CHINA ----------------
    E("confucius.nature", "Confucius", "claim", "nature", "malleable",
      "By nature people are nearly alike; it is practice and learning that set them far apart.",
      "nature learning practice habit cultivation alike education"),
    E("confucius.ren", "Confucius", "concept", "good", "virtue-ritual",
      "Cultivate humaneness (ren) and ritual propriety (li) to become a noble person (junzi).",
      "ren humaneness benevolence li ritual junzi virtue cultivation"),
    E("confucius.goldenrule", "Confucius", "rule", "ahimsa", "golden-rule",
      "Do not impose on others what you yourself do not desire (the principle of shu).",
      "reciprocity golden rule shu others do not impose empathy", "己所不欲，勿施於人"),
    E("confucius.governvirtue", "Confucius", "claim", "order", "rule-by-virtue",
      "Govern by virtue and moral example, not by force; first rectify the names.",
      "virtue government example de rectification names harmony moral"),
    E("mencius.good", "Mencius", "claim", "nature", "good",
      "Human nature is innately good; everyone is born with the four sprouts of virtue.",
      "human nature good four sprouts compassion innate heart born"),
    E("mencius.mandate", "Mencius", "claim", "order", "rule-by-virtue",
      "The ruler holds the Mandate of Heaven through the people's welfare; a tyrant may be deposed.",
      "mandate heaven people welfare benevolent rebellion legitimacy tyrant"),
    E("xunzi.bad", "Xunzi", "claim", "nature", "bad",
      "Human nature is bad/crooked; goodness is the achievement of ritual and conscious effort.",
      "human nature bad evil crooked ritual effort straighten deliberate"),
    E("xunzi.heaven", "Xunzi", "claim", "divine", "naturalist",
      "Heaven operates by constant natural law and sends no omens; do not pray to it but order yourself.",
      "heaven nature constant law naturalism no providence omens secular"),
    E("laozi.dao", "Laozi", "concept", "arche", "monist-abstract",
      "The Dao that can be named is not the eternal Dao — the nameless source prior to Heaven and Earth.",
      "dao way nameless source origin mother mystery", "道可道，非常道"),
    E("laozi.wuwei", "Laozi", "rule", "order", "non-action",
      "Govern by non-action (wuwei); the very best ruler is one whose people scarcely know he exists.",
      "wuwei non-action natural ruler minimal government less laissez"),
    E("laozi.water", "Laozi", "concept", "good", "yielding",
      "The soft and yielding overcomes the hard and strong; be like water.",
      "soft yielding water weakness humility natural overcome flexible"),
    E("zhuangzi.perspective", "Zhuangzi", "concept", "knowledge", "skeptic",
      "Right and wrong, great and small are relative to one's standpoint — am I a man dreaming a butterfly?",
      "relative perspective butterfly dream equality standpoint skepticism things"),
    E("zhuangzi.transformation", "Zhuangzi", "concept", "liberation", "harmony-with-nature",
      "Roam free by following the Dao and accepting every transformation, death included.",
      "free transformation acceptance death natural wandering harmony flow"),
    E("mozi.universal-love", "Mozi", "claim", "ahimsa", "universal-love",
      "Practice impartial, universal love (jian'ai): care for others' families and states as your own.",
      "universal love impartial jianai care others benefit all inclusive"),
    E("mozi.utility", "Mozi", "method", "good", "consequentialist",
      "Judge every practice by its benefit to the people — wealth, order and population.",
      "benefit utility consequence welfare use measure people outcome"),
    E("mozi.anti-war", "Mozi", "claim", "ahimsa", "anti-war",
      "Offensive war is mass murder writ large and the greatest of crimes; condemn aggression.",
      "anti-war aggression condemn offense murder peace nonaggression"),
    E("shangyang.law", "Shang Yang", "claim", "order", "rule-by-law",
      "Order the state by strict, uniform law with heavy punishments and reliable rewards.",
      "law fa punishment reward strict uniform state legalism control"),
    E("shangyang.selfish", "Shang Yang", "claim", "nature", "self-interested",
      "People naturally seek their own gain; harness this with law, not with moral preaching.",
      "self-interest selfish gain law incentives human nature control"),
    E("hanfeizi.law", "Han Feizi", "claim", "order", "rule-by-law",
      "The ruler keeps order through law (fa), administrative method (shu) and positional power (shi).",
      "law method power fa shu shi ruler statecraft legalism authority"),
    E("hanfeizi.distrust", "Han Feizi", "claim", "nature", "self-interested",
      "Do not count on people being good; count on making wrongdoing impossible.",
      "self-interest distrust incentives human nature control institutions"),
    E("sunzi.strategy", "Sun Tzu", "rule", "good", "strategy-adaptation",
      "Supreme excellence is to subdue the enemy without fighting; all warfare is based on deception.",
      "strategy war deception victory without fighting adapt formless terrain"),
    E("gongsunlong.names", "Gongsun Long", "claim", "knowledge", "logic-language",
      "A white horse is not a horse: a name marks a class, and class is not identity.",
      "names logic white horse paradox language class distinction reference"),

    # ---------------- INDIA ----------------
    E("vedas.nasadiya", "Vedas", "question", "arche", "monist-abstract",
      "In the beginning was neither being nor non-being; perhaps even the gods do not know whence creation came.",
      "creation origin nasadiya doubt one breath being nonbeing mystery"),
    E("vedas.rta", "Vedas", "concept", "justice", "cosmic-order",
      "The cosmos is upheld by Ṛta — the impersonal order of truth and right.",
      "rta order truth cosmic law right harmony"),
    E("upanishads.brahman", "Upanishads", "claim", "reality", "idealist",
      "Brahman is the single ultimate reality underlying every appearance.",
      "brahman absolute one reality nondual ground being"),
    E("upanishads.atman", "Upanishads", "claim", "self", "eternal-self",
      "The inmost self (Ātman) is identical with Brahman: 'That thou art' (tat tvam asi).",
      "atman brahman self identity nondual eternal soul unity", "तत् त्वम् असि"),
    E("upanishads.moksha", "Upanishads", "concept", "liberation", "release-rebirth",
      "Liberation (mokṣa) is release from the cycle of rebirth, won by knowing the Self.",
      "moksha liberation rebirth samsara knowledge release freedom"),
    E("upanishads.karma", "Upanishads", "concept", "justice", "karma",
      "By good action one becomes good, by evil evil; deeds bind the self to rebirth (karma).",
      "karma action deeds rebirth moral causation consequence"),
    E("mahavira.ahimsa", "Mahavira", "rule", "ahimsa", "non-violence",
      "Non-violence (ahiṃsā) toward every living being is the highest religion and duty.",
      "ahimsa nonviolence jain living beings harm compassion duty"),
    E("mahavira.anekanta", "Mahavira", "method", "knowledge", "skeptic",
      "Truth is many-sided (anekāntavāda); every single view is partial, like blind men feeling an elephant.",
      "anekanta many-sided perspective partial elephant relativity viewpoint"),
    E("mahavira.jiva", "Mahavira", "claim", "liberation", "release-rebirth",
      "Each soul (jīva) is weighed down by karmic matter; freeing it brings omniscient bliss.",
      "jiva soul karma bondage liberation kevala omniscient release"),
    E("buddha.fourtruths", "Buddha", "claim", "liberation", "release-rebirth",
      "Life is suffering (dukkha); suffering arises from craving; ending craving ends suffering — the Four Noble Truths.",
      "suffering dukkha craving cessation four noble truths eightfold path nirvana"),
    E("buddha.anatta", "Buddha", "claim", "self", "no-self",
      "There is no permanent self (anattā); a person is only a stream of changing aggregates.",
      "anatta no-self nonself aggregates impermanent self stream"),
    E("buddha.anicca", "Buddha", "concept", "change", "flux",
      "All conditioned things are impermanent (anicca), forever arising and passing away.",
      "impermanence anicca change flux transient arising passing"),
    E("buddha.middleway", "Buddha", "rule", "good", "virtue-mean",
      "Avoid both sensual indulgence and harsh self-mortification: walk the Middle Way.",
      "middle way moderation balance extremes indulgence asceticism"),
    E("buddha.karma", "Buddha", "concept", "justice", "karma",
      "Intentional action (karma) conditions rebirth and shapes one's destiny.",
      "karma action intention rebirth cause moral consequence"),
    E("gosala.determinism", "Makkhali Gosala", "claim", "fate", "determinism",
      "All is fixed by fate (niyati); effort and will change nothing — beings are purified by destiny alone.",
      "niyati fate determinism no free will destiny inevitable predestination"),
    E("carvaka.materialism", "Carvaka", "claim", "reality", "materialist",
      "Only matter known through the senses is real; consciousness is a by-product of the body.",
      "materialism matter body consciousness lokayata physical senses"),
    E("carvaka.nosoul", "Carvaka", "claim", "self", "mortal-material",
      "There is no soul, no rebirth and no afterlife; when the body dies, the person ends.",
      "no soul no afterlife death annihilation body mortal end"),
    E("carvaka.empiricism", "Carvaka", "claim", "knowledge", "empiricism-only",
      "Only perception is a valid source of knowledge; inference and scripture cannot be trusted.",
      "perception empiricism senses no inference no scripture evidence"),
    E("carvaka.hedonism", "Carvaka", "claim", "good", "hedonist",
      "While you live, live well and enjoy pleasure, for once burned the body never returns.",
      "pleasure enjoy hedonism body this life eat drink"),
    E("kapila.dualism", "Kapila", "claim", "reality", "dualist",
      "Reality is twofold: conscious witness (puruṣa) and unconscious primal matter (prakṛti).",
      "purusha prakriti dualism spirit matter samkhya witness nature"),
    E("kapila.liberation", "Kapila", "concept", "liberation", "release-rebirth",
      "Liberation comes from discriminating the witnessing self from material nature.",
      "liberation discrimination purusha detachment release knowledge"),
    E("panini.grammar", "Panini", "method", "knowledge", "logic-language",
      "Language is generated by a finite, ordered system of formal rules (the Aṣṭādhyāyī).",
      "grammar rules language formal generative sanskrit system algorithm"),

    # ---------------- PERSIA ----------------
    E("zoroaster.dualism", "Zoroaster", "claim", "divine", "ethical-dualism",
      "Existence is a contest between Ahura Mazda, the Wise Lord, and the hostile spirit Angra Mainyu.",
      "dualism ahura mazda angra mainyu good evil two spirits cosmic struggle"),
    E("zoroaster.free-choice", "Zoroaster", "claim", "fate", "free-will",
      "Each person must choose freely between truth (asha) and the lie (druj).",
      "free choice asha druj truth lie moral choice will responsibility"),
    E("zoroaster.asha", "Zoroaster", "concept", "justice", "cosmic-order",
      "The world is upheld by Asha — truth and right order — against Druj, the Lie.",
      "asha truth order righteousness druj lie cosmic moral"),
    E("zoroaster.judgment", "Zoroaster", "concept", "liberation", "final-judgment",
      "History moves toward a final renewal, and each soul is judged by its thoughts, words and deeds.",
      "judgment renewal afterlife thoughts words deeds eschatology resurrection"),

    # ---------------- ISRAEL ----------------
    E("proverbs.fear", "Proverbs", "claim", "knowledge", "revealed-wisdom",
      "The fear of the LORD is the beginning of wisdom.",
      "wisdom fear lord beginning knowledge instruction reverence"),
    E("proverbs.wisdom", "Proverbs", "concept", "justice", "cosmic-order",
      "Wisdom (Ḥokhmah) was beside God at creation, ordering the world in righteousness.",
      "wisdom creation order righteousness hokhmah design"),
    E("ecclesiastes.vanity", "Ecclesiastes", "claim", "liberation", "mortality-meaning",
      "Vanity of vanities — all is fleeting breath (hevel); there is nothing new under the sun.",
      "vanity hevel fleeting breath meaning death nothing new", "הֲבֵל הֲבָלִים"),
    E("ecclesiastes.enjoy", "Ecclesiastes", "rule", "good", "tranquility",
      "There is nothing better for a person than to eat, drink and find enjoyment in their toil.",
      "enjoy simple toil contentment present eat drink portion"),
    E("job.suffering", "Job", "question", "liberation", "mortality-meaning",
      "The righteous may suffer without explanation; God's ways exceed all human understanding.",
      "suffering theodicy righteous unanswered whirlwind innocent mystery"),
    E("torah.monotheism", "Torah", "claim", "divine", "monotheism",
      "There is one God, maker of heaven and earth, who requires justice and mercy of all.",
      "one god monotheism creator covenant justice mercy ethical"),
    E("torah.neighbor", "Torah", "rule", "ahimsa", "golden-rule",
      "Love your neighbor as yourself.",
      "love neighbor golden rule others as yourself empathy", "וְאָהַבְתָּ לְרֵעֲךָ כָּמוֹךָ"),
    E("torah.talion", "Torah", "rule", "justice", "retributive-law",
      "Measure for measure: an eye for an eye, a tooth for a tooth, a life for a life.",
      "eye for eye retribution talion measure proportion law"),
    E("prophets.justice", "Prophets", "claim", "order", "rule-by-virtue",
      "Let justice roll down like waters; God desires righteousness and mercy, not sacrifice.",
      "justice righteousness sacrifice prophets social mercy oppression"),

    # ---------------- EGYPT ----------------
    E("ptahhotep.humility", "Ptahhotep", "rule", "good", "virtue-ritual",
      "Be humble and listen; fine speech is rarer than emerald, yet found even among servant girls.",
      "humility speech listening wisdom maxim instruction modesty"),
    E("ptahhotep.maat", "Ptahhotep", "concept", "justice", "cosmic-order",
      "Do Ma'at as long as you live; it endures, while wrongdoing never brings its cargo safe to harbor.",
      "maat truth justice order righteousness endures wrongdoing"),
    E("amenemope.silent", "Amenemope", "rule", "good", "tranquility",
      "Better is the silent, self-controlled man than one who is rich and hot of mouth.",
      "silent man contentment patience moderation calm self-control"),
    E("akhenaten.aten", "Akhenaten", "claim", "divine", "monotheism",
      "The Aten, the sole living sun-disc, is the one creator of every land and all that lives.",
      "aten sun one creator monotheism akhenaten light universal"),
    E("dispute.death", "Dispute with the Ba", "claim", "liberation", "mortality-meaning",
      "When life is heavy with grief, death stands before me like the scent of myrrh, like recovery from illness.",
      "death suffering grief longing soul ba release relief"),
    E("bookdead.heart", "Book of the Dead", "concept", "justice", "final-judgment",
      "After death the heart is weighed against the feather of Ma'at; the just pass on to eternal life.",
      "weighing heart maat judgment afterlife feather scales just"),

    # ---------------- MESOPOTAMIA ----------------
    E("shuruppak.prudence", "Instructions of Shuruppak", "rule", "good", "virtue-ritual",
      "Do not steal, do not lie, do not covet; measured, honest dealing makes a life prosper.",
      "instruction maxim prudence honesty advice father son measured"),
    E("gilgamesh.mortality", "Epic of Gilgamesh", "claim", "liberation", "accept-annihilation",
      "Eternal life is kept for the gods; cherish the life, food, and companions you have, for you must die.",
      "mortality death immortality acceptance life companions feast finitude"),
    E("theodicy.suffering", "Babylonian Theodicy", "question", "liberation", "mortality-meaning",
      "The righteous too are struck by inexplicable suffering; the minds of the gods are remote.",
      "suffering theodicy righteous gods remote injustice complaint"),
    E("dialogue.futility", "Dialogue of Pessimism", "claim", "knowledge", "skeptic",
      "Every purpose can be argued for and then against; perhaps no human plan finally matters.",
      "futility pessimism nothing matters irony doubt purpose reversal"),
    E("hammurabi.talion", "Hammurabi", "rule", "justice", "retributive-law",
      "Law is set in stone that the strong may not oppress the weak — an eye for an eye.",
      "law justice eye for eye retribution code strong weak talion stele"),
    E("enuma.order", "Enuma Elish", "concept", "arche", "order-from-chaos",
      "Order (Marduk) is fashioned out of primordial chaos (Tiamat); the cosmos is wrought from conflict.",
      "chaos order creation marduk tiamat cosmogony conflict primordial"),
]

# antonym cue pairs that signal a contradiction when both keywords appear across a pair
ANTONYMS = [
    ("flux", "changeless"), ("change", "changeless"), ("impermanence", "eternal"),
    ("impermanent", "eternal"), ("motion", "motionless"), ("good", "evil"),
    ("good", "bad"), ("free", "fate"), ("free", "determinism"), ("will", "destiny"),
    ("soul", "no soul"), ("immortal", "mortal"), ("rebirth", "annihilation"),
    ("matter", "form"), ("matter", "mind"), ("senses", "reason"),
    ("perception", "reason"), ("pleasure", "virtue"), ("law", "virtue"),
    ("one god", "two spirits"), ("monotheism", "dualism"), ("being", "nonbeing"),
    ("non-action", "law"), ("universal love", "punishment"),
]

# Dual-language canonical quotes: element id -> (original / transliteration, English).
# Only quotes we can attest are included; archaic scripts we cannot verify are given
# in standard scholarly romanization rather than invented glyphs.
QUOTES = {
    # Greece
    "heraclitus.flux":      ("πάντα ῥεῖ", "everything flows"),
    "protagoras.measure":   ("πάντων χρημάτων μέτρον ἄνθρωπος", "man is the measure of all things"),
    "socrates.examined":    ("ὁ ἀνεξέταστος βίος οὐ βιωτὸς ἀνθρώπῳ", "the unexamined life is not worth living"),
    "socrates.ignorance":   ("ἓν οἶδα ὅτι οὐδὲν οἶδα", "I know one thing — that I know nothing"),
    "parmenides.being":     ("τὸ γὰρ αὐτὸ νοεῖν ἐστίν τε καὶ εἶναι", "to think and to be are the same"),
    "aristotle.mean":       ("μεσότης", "the mean between the extremes"),
    "plato.forms":          ("εἶδος", "Form / Idea"),
    # China
    "laozi.dao":            ("道可道，非常道", "the Way that can be spoken is not the eternal Way"),
    "confucius.goldenrule": ("己所不欲，勿施於人", "do not impose on others what you do not desire"),
    "zhuangzi.perspective": ("莊周夢蝶", "Zhuang Zhou dreams he is a butterfly"),
    "mozi.universal-love":  ("兼愛", "impartial, all-embracing love (jiān'ài)"),
    # India
    "upanishads.atman":     ("तत् त्वम् असि", "that thou art"),
    "buddha.anicca":        ("sabbe saṅkhārā aniccā", "all conditioned things are impermanent"),
    "mahavira.ahimsa":      ("ahiṃsā paramo dharmaḥ", "non-violence is the highest law"),
    # Persia
    "zoroaster.free-choice":("humata · hūxta · huuaršta", "good thoughts, good words, good deeds"),
    # Israel
    "ecclesiastes.vanity":  ("הֲבֵל הֲבָלִים", "vanity of vanities"),
    "torah.neighbor":       ("וְאָהַבְתָּ לְרֵעֲךָ כָּמוֹךָ", "love your neighbor as yourself"),
    "torah.talion":         ("עַיִן תַּחַת עַיִן", "an eye for an eye"),
    "torah.monotheism":     ("שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד", "Hear, O Israel: the LORD our God, the LORD is one"),
    "proverbs.fear":        ("רֵאשִׁית חָכְמָה יִרְאַת יְהוָה", "the beginning of wisdom is the fear of the LORD"),
    # Egypt
    "ptahhotep.maat":       ("mꜣꜥt", "Maʿat — truth, justice and cosmic order"),
    # Mesopotamia
    "gilgamesh.mortality":  ("ša naqba īmuru", "he who saw the Deep"),
    "enuma.order":          ("Enūma eliš lā nabû šamāmū", "when on high the heavens had not been named"),
}

# Native-language technical TERM (the "idea") for every concept without a full quote,
# as (native, English gloss) so the two are a matched pair rather than the short native
# term sitting under the long English statement. The gloss translates the TERM, not the
# whole doctrine (which is the element's `text`). Script drives the speech voice.
TERMS = {
    # --- Greece (Greek) ---
    "thales.water": ("ὕδωρ", "water"), "thales.hylozoism": ("ἔμψυχον", "ensouled / alive"),
    "anaximander.apeiron": ("ἄπειρον", "the boundless"), "anaximander.recompense": ("δίκη", "justice"),
    "anaximander.evolution": ("γένεσις", "coming-to-be"), "anaximenes.air": ("ἀήρ", "air"),
    "pythagoras.number": ("ἀριθμός", "number"), "pythagoras.soul": ("μετεμψύχωσις", "transmigration of souls"),
    "pythagoras.harmony": ("ἁρμονία", "harmony"), "xenophanes.onegod": ("εἷς θεός", "one god"),
    "xenophanes.limits": ("δόξα", "opinion / seeming"), "heraclitus.logos": ("λόγος", "the Logos / reason"),
    "heraclitus.opposites": ("τὰ ἐναντία", "the opposites"), "parmenides.reason": ("νόος", "reason / mind"),
    "zeno.paradox": ("Ἀχιλλεύς", "Achilles (the paradox)"), "empedocles.roots": ("ῥιζώματα", "the four roots"),
    "empedocles.transmigration": ("δαίμων", "the fallen spirit"), "anaxagoras.nous": ("νοῦς", "Mind"),
    "democritus.atoms": ("ἄτομα", "atoms"), "democritus.convention": ("νόμῳ", "by convention"),
    "democritus.euthymia": ("εὐθυμία", "cheerfulness"), "protagoras.agnostic": ("περὶ θεῶν", "concerning the gods"),
    "gorgias.nihilism": ("οὐδὲν ἔστιν", "nothing exists"), "socrates.virtue": ("ἀρετή", "virtue / excellence"),
    "plato.soul": ("ψυχὴ ἀθάνατος", "the immortal soul"), "plato.philosopherking": ("φιλόσοφος βασιλεύς", "philosopher-king"),
    "plato.justice": ("δικαιοσύνη", "justice"), "aristotle.hylomorphism": ("ὕλη καὶ μορφή", "matter and form"),
    "aristotle.causes": ("τὰ τέτταρα αἴτια", "the four causes"), "aristotle.mover": ("πρῶτον κινοῦν ἀκίνητον", "the unmoved mover"),
    "aristotle.political": ("ζῷον πολιτικόν", "political animal"), "diogenes.asceticism": ("αὐτάρκεια", "self-sufficiency"),
    "diogenes.cosmopolitan": ("κοσμοπολίτης", "citizen of the world"), "epicurus.pleasure": ("ἡδονή", "pleasure"),
    "epicurus.death": ("ὁ θάνατος οὐδὲν πρὸς ἡμᾶς", "death is nothing to us"), "epicurus.atoms": ("ἄτομα καὶ κενόν", "atoms and void"),
    "epicurus.gods": ("μακάριον καὶ ἄφθαρτον", "blessed and imperishable"), "zenocitium.virtue": ("ὁμολογουμένως τῇ φύσει ζῆν", "live in agreement with nature"),
    "zenocitium.fate": ("εἱμαρμένη", "fate"),
    # --- China (Chinese) ---
    "confucius.nature": ("性相近", "natures are alike"), "confucius.ren": ("仁", "benevolence / humaneness"),
    "confucius.governvirtue": ("德治", "rule by virtue"), "mencius.good": ("性善", "human nature is good"),
    "mencius.mandate": ("天命", "the Mandate of Heaven"), "xunzi.bad": ("性惡", "human nature is bad"),
    "xunzi.heaven": ("天行有常", "Heaven acts with constancy"), "laozi.wuwei": ("無為", "non-action"),
    "laozi.water": ("上善若水", "the highest good is like water"), "zhuangzi.transformation": ("逍遙遊", "free and easy wandering"),
    "mozi.utility": ("利", "benefit"), "mozi.anti-war": ("非攻", "against offensive war"),
    "shangyang.law": ("法", "law"), "shangyang.selfish": ("趨利避害", "seek gain, avoid harm"),
    "hanfeizi.law": ("法術勢", "law, method, power"), "hanfeizi.distrust": ("自利", "self-interest"),
    "sunzi.strategy": ("不戰而屈人之兵", "subdue the enemy without fighting"), "gongsunlong.names": ("白馬非馬", "a white horse is not a horse"),
    # --- India (Sanskrit / Devanagari) ---
    "vedas.nasadiya": ("नासदीय सूक्त", "the Hymn of Creation"), "vedas.rta": ("ऋत", "cosmic order"),
    "upanishads.brahman": ("ब्रह्मन्", "Brahman (the Absolute)"), "upanishads.moksha": ("मोक्ष", "liberation"),
    "upanishads.karma": ("कर्म", "action / karma"), "mahavira.anekanta": ("अनेकान्तवाद", "many-sidedness of truth"),
    "mahavira.jiva": ("जीव", "the soul"), "buddha.fourtruths": ("निर्वाण", "nirvana"),
    "buddha.anatta": ("अनात्मन्", "non-self"), "buddha.middleway": ("मध्यम मार्ग", "the Middle Way"),
    "buddha.karma": ("कर्म", "action / karma"), "gosala.determinism": ("नियति", "fate / determinism"),
    "carvaka.materialism": ("लोकायत", "materialism (Lokāyata)"), "carvaka.nosoul": ("देहात्मवाद", "the body is the self"),
    "carvaka.empiricism": ("प्रत्यक्ष", "perception"), "carvaka.hedonism": ("सुख", "pleasure"),
    "kapila.dualism": ("पुरुष प्रकृति", "spirit and matter"), "kapila.liberation": ("कैवल्य", "liberation (kaivalya)"),
    "panini.grammar": ("व्याकरण", "grammar"),
    # --- Persia (Persian / romanized Avestan) ---
    "zoroaster.dualism": ("اهورا مزدا", "Ahura Mazda (the Wise Lord)"), "zoroaster.asha": ("اشا", "truth / cosmic order"),
    "zoroaster.judgment": ("Frašōkərəti", "the final renewal"),
    # --- Israel (Hebrew) ---
    "proverbs.wisdom": ("חׇכְמָה", "Wisdom (Ḥokhmah)"), "ecclesiastes.enjoy": ("שִׂמְחָה", "joy"),
    "job.suffering": ("צַדִּיק", "the righteous one"), "prophets.justice": ("צֶדֶק", "justice / righteousness"),
    # --- Egypt (romanized) ---
    "ptahhotep.humility": ("sḏm", "to listen"), "amenemope.silent": ("gr", "the silent man"),
    "akhenaten.aten": ("jtn", "the Aten (sun-disc)"), "dispute.death": ("bꜣ", "the ba (soul)"),
    "bookdead.heart": ("jb", "the heart"),
    # --- Mesopotamia (romanized) ---
    "shuruppak.prudence": ("milku", "counsel"), "theodicy.suffering": ("šīmtu", "fate"),
    "dialogue.futility": ("ṭēmu", "plan / reason"), "hammurabi.talion": ("kittum u mīšarum", "truth and justice"),
}

# Cuneiform author/work names → romanization so the "author" pronunciation is speakable.
AUTHOR_ROMAN = {
    "Instructions of Shuruppak": "Šuruppak", "Epic of Gilgamesh": "Gilgāmeš",
    "Hammurabi": "Ḫammurabi", "Enuma Elish": "Enūma Eliš",
}

# Romanized speech fallback for scripts most systems have no TTS voice for (Persian/
# Avestan in Arabic script): if no matching voice is found, the button reads this instead.
ROMAN = {
    "زرتشت": "Zarathushtra", "اهورا مزدا": "Ahura Mazda", "اشا": "Asha",
}

# Modern-language version of each statement, in the region's living tongue, so every idea
# has a native rendering + voice. These are AI-generated MODERN translations (Egyptian &
# Mesopotamian rendered in Arabic, the modern regional language) — not sourced originals.
STATEMENT_LANG = {
    "Greece": "el-GR", "China": "zh-CN", "India": "hi-IN", "Persia": "fa-IR",
    "Israel": "he-IL", "Egypt": "ar", "Mesopotamia": "ar",
}
STMT = {
    # ---- Greece (Modern Greek) ----
    "thales.water": "Το νερό είναι η θεμελιώδης αρχή απ' την οποία προέρχονται τα πάντα.",
    "thales.hylozoism": "Τα πάντα είναι γεμάτα θεούς· ακόμη κι ο μαγνήτης έχει ψυχή, γιατί ο κόσμος είναι ζωντανός.",
    "anaximander.apeiron": "Η αρχή των πάντων είναι το άπειρο — το απεριόριστο, αόριστο κι αιώνιο.",
    "anaximander.recompense": "Τα όντα πληρώνουν το ένα στο άλλο δίκη και τιμωρία για την αδικία τους, κατά την τάξη του χρόνου.",
    "anaximander.evolution": "Τα έμβια όντα γεννήθηκαν από την υγρασία· ο άνθρωπος πρωτοαναπτύχθηκε μέσα σε άλλα ζώα.",
    "anaximenes.air": "Ο αέρας είναι η πρώτη ουσία· με πύκνωση κι αραίωση γίνεται τα πάντα.",
    "pythagoras.number": "Ο αριθμός είναι η ουσία και η δομή κάθε πραγματικότητας· ο κόσμος τακτοποιείται με αναλογίες.",
    "pythagoras.soul": "Η ψυχή είναι αθάνατη και μετενσαρκώνεται σε διαδοχικά σώματα.",
    "pythagoras.harmony": "Κάθαρε και συντόνισε την ψυχή με την αρμονία, όπως οι μουσικές αναλογίες κουρδίζουν τη λύρα.",
    "xenophanes.onegod": "Οι θνητοί φαντάζονται τους θεούς κατ' εικόνα τους· στ' αλήθεια υπάρχει ένας ύψιστος θεός, ανόμοιος με τους θνητούς.",
    "xenophanes.limits": "Κανείς δεν είδε ούτε θα γνωρίσει τη βέβαιη αλήθεια· πάνω σ' όλα υπάρχει μόνο δοκησισοφία.",
    "heraclitus.flux": "Τα πάντα ρέουν· δεν μπορείς να μπεις δυο φορές στο ίδιο ποτάμι.",
    "heraclitus.logos": "Τα πάντα συμβαίνουν σύμφωνα με τον Λόγο — τον έναν καθολικό νόμο και λόγο.",
    "heraclitus.opposites": "Τα αντίθετα είναι ένα· η έριδα είναι δικαιοσύνη, κι ο κόσμος μια αείζωη φωτιά.",
    "parmenides.being": "Το ον είναι και δεν μπορεί να μην είναι· ό,τι πραγματικά υπάρχει είναι ένα, αγέννητο κι αμετάβλητο.",
    "parmenides.reason": "Ακολούθησε τον λόγο, όχι τις απατηλές αισθήσεις· η μεταβολή κι η πολλαπλότητα είναι ψευδαίσθηση.",
    "zeno.paradox": "Η κίνηση είναι αδύνατη — ο Αχιλλέας δεν προλαβαίνει ποτέ τη χελώνα· η πολλαπλότητα οδηγεί σ' αντίφαση.",
    "empedocles.roots": "Τα πάντα προέρχονται από τέσσερις ρίζες — γη, νερό, αέρα, φωτιά — που ενώνει η Φιλότητα και χωρίζει το Νείκος.",
    "empedocles.transmigration": "Το πεσμένο πνεύμα ξαναγεννιέται σε φυτά, ζώα κι ανθρώπους· απέχε από την αιματοχυσία.",
    "anaxagoras.nous": "Ο Νους βάζει τα πάντα σε τάξη· σε κάθε πράγμα υπάρχει ένα μέρος απ' το καθετί.",
    "democritus.atoms": "Δεν υπάρχει τίποτε άλλο παρά άτομα και κενό· κάθε μεταβολή είναι μόνο άτομα που ενώνονται και χωρίζονται.",
    "democritus.convention": "Το γλυκό και το πικρό υπάρχουν κατά σύμβαση· στην πραγματικότητα υπάρχουν μόνο άτομα και κενό.",
    "democritus.euthymia": "Σκοπός της ζωής είναι η ευθυμία — ένας ήρεμος, ικανοποιημένος κι άφοβος νους.",
    "protagoras.measure": "Ο άνθρωπος είναι το μέτρο όλων των πραγμάτων — η αλήθεια είναι σχετική ως προς αυτόν που την αντιλαμβάνεται.",
    "protagoras.agnostic": "Για τους θεούς δεν μπορώ να ξέρω ούτε αν υπάρχουν ούτε τι λογής είναι.",
    "gorgias.nihilism": "Τίποτε δεν υπάρχει· κι αν υπήρχε, δεν θα μπορούσε να γίνει γνωστό· κι αν γινόταν, δεν θα μπορούσε να μεταδοθεί.",
    "socrates.virtue": "Η αρετή είναι γνώση· κανείς δεν σφάλλει εκούσια, παρά μόνο από άγνοια.",
    "socrates.ignorance": "Η μόνη αληθινή σοφία είναι να ξέρεις ότι δεν ξέρεις τίποτε.",
    "socrates.examined": "Η ανεξέταστη ζωή δεν αξίζει να τη ζει κανείς.",
    "plato.forms": "Πέρα απ' τον μεταβαλλόμενο κόσμο των αισθήσεων βρίσκεται ο αιώνιος, τέλειος κόσμος των Ιδεών.",
    "plato.soul": "Η ψυχή είναι αθάνατη και τριμερής — λογικό, θυμοειδές κι επιθυμητικό — και ξαναγεννιέται.",
    "plato.philosopherking": "Η δίκαιη πόλη πρέπει να κυβερνιέται από φιλοσόφους-βασιλείς που γνωρίζουν το Αγαθό.",
    "plato.justice": "Δικαιοσύνη είναι η αρμονία — κάθε μέρος της ψυχής και της πόλης να κάνει το έργο που του αρμόζει.",
    "aristotle.mean": "Η αρετή είναι μεσότητα ανάμεσα στα άκρα, που διαμορφώνεται με τη συνήθεια· σκοπός της ζωής είναι η ευδαιμονία.",
    "aristotle.hylomorphism": "Κάθε ουσία είναι ένωση μορφής και ύλης· η ψυχή είναι η μορφή του ζωντανού σώματος.",
    "aristotle.causes": "Να γνωρίζεις κάτι σημαίνει να γνωρίζεις τα τέσσερα αίτιά του — υλικό, μορφικό, ποιητικό και τελικό.",
    "aristotle.mover": "Κάθε κίνηση ανάγεται σ' ένα Πρώτο Ακίνητο Κινούν — καθαρή ενέργεια, νόηση που νοεί τον εαυτό της.",
    "aristotle.political": "Ο άνθρωπος είναι εκ φύσεως πολιτικό ζώο· η πόλη υπάρχει χάριν της καλής ζωής.",
    "diogenes.asceticism": "Η αρετή είναι το μόνο αγαθό· ζήσε αυτάρκης, ελεύθερος από συμβάσεις κι επιθυμίες.",
    "diogenes.cosmopolitan": "Όταν τον ρώτησαν από πού είναι, είπε: «Είμαι πολίτης του κόσμου».",
    "epicurus.pleasure": "Η ηδονή — η απαλλαγή απ' τον σωματικό πόνο και την ψυχική ταραχή — είναι ο σκοπός της ζωής.",
    "epicurus.death": "Ο θάνατος δεν είναι τίποτε για μας: όσο υπάρχουμε δεν υπάρχει, κι όταν υπάρχει δεν υπάρχουμε εμείς.",
    "epicurus.atoms": "Το σύμπαν είναι μόνο άτομα και κενό, άπειρο και χωρίς καμία θεϊκή διακυβέρνηση.",
    "epicurus.gods": "Οι θεοί υπάρχουν, μα είναι μακάριοι κι αθάνατοι, και δεν νοιάζονται για τα ανθρώπινα.",
    "zenocitium.virtue": "Ζήσε σύμφωνα με τη φύση και τον λόγο· μόνο η αρετή είναι αγαθό, όλα τα εξωτερικά αδιάφορα.",
    "zenocitium.fate": "Το σύμπαν κυβερνάται απ' τον θεϊκό λόγο· δέξου τη μοίρα με αταραξία.",
    # ---- China (Mandarin) ----
    "confucius.nature": "人的本性相近，是习染与学习使人相去甚远。",
    "confucius.ren": "修养仁与礼，方能成为君子。",
    "confucius.goldenrule": "己所不欲，勿施于人。",
    "confucius.governvirtue": "以德治国、以身作则，而非以力；先正名分。",
    "mencius.good": "人性本善，人人生来皆有四端。",
    "mencius.mandate": "君主凭民心而受天命；暴君可被推翻。",
    "xunzi.bad": "人性本恶，善乃后天礼法与努力所成。",
    "xunzi.heaven": "天行有常，不因人而改，也不降征兆；与其祈祷，不如修治自身。",
    "laozi.dao": "可以言说的道，不是永恒的道；它是天地之先、无名的本源。",
    "laozi.wuwei": "以无为而治；最好的君主，百姓几乎感觉不到他的存在。",
    "laozi.water": "柔弱胜刚强；要像水一样。",
    "zhuangzi.perspective": "是非、大小皆相对于立场——我究竟是人在梦蝶，还是蝶在梦人？",
    "zhuangzi.transformation": "顺应大道，接受一切变化，包括死亡，逍遥自在。",
    "mozi.universal-love": "行兼爱：像爱自己一样爱他人的家与国。",
    "mozi.utility": "以是否利于百姓——富庶、安定、人口——来衡量一切。",
    "mozi.anti-war": "侵略战争是大规模的谋杀，是最大的罪行；应谴责侵略。",
    "shangyang.law": "以严明统一的法律、重罚与信赏来治理国家。",
    "shangyang.selfish": "人天性追逐私利；应以法律驾驭，而非道德说教。",
    "hanfeizi.law": "君主以法、术、势来维持秩序。",
    "hanfeizi.distrust": "不要指望人人为善，而要使作恶成为不可能。",
    "sunzi.strategy": "不战而屈人之兵，善之善者也；兵者，诡道也。",
    "gongsunlong.names": "白马非马：名指称一类，而类不等于个体。",
    # ---- India (Hindi) ----
    "vedas.nasadiya": "आरम्भ में न सत् था न असत्; शायद देवता भी नहीं जानते कि सृष्टि कहाँ से आई।",
    "vedas.rta": "यह ब्रह्माण्ड ऋत—सत्य और नियम की अवैयक्तिक व्यवस्था—पर टिका है।",
    "upanishads.brahman": "ब्रह्म ही एकमात्र परम सत्य है, जो हर आभास के मूल में है।",
    "upanishads.atman": "अन्तरात्मा ब्रह्म से अभिन्न है: 'तत् त्वम् असि' (वह तू है)।",
    "upanishads.moksha": "मोक्ष आत्मा को जानकर जन्म-मरण के चक्र से मुक्ति है।",
    "upanishads.karma": "अच्छे कर्म से मनुष्य अच्छा, बुरे से बुरा बनता है; कर्म आत्मा को पुनर्जन्म से बाँधते हैं।",
    "mahavira.ahimsa": "हर प्राणी के प्रति अहिंसा ही सर्वोच्च धर्म और कर्तव्य है।",
    "mahavira.anekanta": "सत्य अनेकांत है; हर दृष्टिकोण आंशिक है, जैसे अंधे हाथी को टटोलते हैं।",
    "mahavira.jiva": "हर जीव कर्म-पदार्थ से बँधा है; उसे मुक्त करने पर सर्वज्ञ आनन्द मिलता है।",
    "buddha.fourtruths": "जीवन दुःख है; दुःख तृष्णा से उठता है; तृष्णा के अन्त से दुःख का अन्त—यही चार आर्य सत्य हैं।",
    "buddha.anatta": "कोई स्थायी आत्मा नहीं (अनात्म); व्यक्ति केवल बदलते स्कंधों का प्रवाह है।",
    "buddha.anicca": "सभी संस्कार अनित्य हैं, निरन्तर उत्पन्न और नष्ट होते रहते हैं।",
    "buddha.middleway": "इन्द्रिय-भोग और कठोर तपस्या दोनों से बचो: मध्यम मार्ग पर चलो।",
    "buddha.karma": "सचेत कर्म पुनर्जन्म को निर्धारित करता है और भाग्य को गढ़ता है।",
    "gosala.determinism": "सब कुछ नियति से निश्चित है; प्रयास और इच्छा कुछ नहीं बदलते।",
    "carvaka.materialism": "केवल इन्द्रियों से ज्ञात पदार्थ ही सत्य है; चेतना शरीर का उपोत्पाद है।",
    "carvaka.nosoul": "न आत्मा है, न पुनर्जन्म, न परलोक; शरीर के मरते ही व्यक्ति समाप्त।",
    "carvaka.empiricism": "ज्ञान का एकमात्र प्रमाण प्रत्यक्ष है; अनुमान और शास्त्र विश्वसनीय नहीं।",
    "carvaka.hedonism": "जब तक जियो, सुख से जियो; एक बार जल जाने पर शरीर लौटता नहीं।",
    "kapila.dualism": "सत्य द्विविध है: चेतन पुरुष और अचेतन प्रकृति।",
    "kapila.liberation": "मुक्ति साक्षी आत्मा को प्रकृति से विवेकपूर्वक अलग जानने से मिलती है।",
    "panini.grammar": "भाषा नियमों की एक सीमित, व्यवस्थित प्रणाली (अष्टाध्यायी) से उत्पन्न होती है।",
    # ---- Persia (Persian) ----
    "zoroaster.dualism": "هستی نبردی است میان اهورا مزدا، سرور دانا، و انگره مینو، روح ستیزه‌جو.",
    "zoroaster.free-choice": "هر کس باید آزادانه میان راستی (اَشا) و دروغ (دْروج) برگزیند.",
    "zoroaster.asha": "جهان بر پایهٔ اَشا — راستی و نظمِ درست — در برابر دروغ استوار است.",
    "zoroaster.judgment": "تاریخ به‌سوی نوسازیِ نهایی می‌رود و هر روان بر پایهٔ اندیشه، گفتار و کردارش داوری می‌شود.",
    # ---- Israel (Modern Hebrew) ----
    "proverbs.fear": "ראשית החוכמה היא יראת ה'.",
    "proverbs.wisdom": "החוכמה הייתה לצד האל בעת הבריאה, ומסדרת את העולם בצדק.",
    "ecclesiastes.vanity": "הבל הבלים, הכול הבל חולף; אין כל חדש תחת השמש.",
    "ecclesiastes.enjoy": "אין טוב לאדם מלאכול, לשתות ולמצוא שמחה בעמלו.",
    "job.suffering": "הצדיק עשוי לסבול בלא הסבר; דרכי האל נשגבות מבינת אדם.",
    "torah.monotheism": "יש אל אחד, בורא שמים וארץ, הדורש מכולם צדק וחסד.",
    "torah.neighbor": "ואהבת לרעך כמוך.",
    "torah.talion": "מידה כנגד מידה: עין תחת עין, שן תחת שן, נפש תחת נפש.",
    "prophets.justice": "יִגַּל המשפט כמים; האל חפץ בצדק ובחסד, לא בקורבן.",
    # ---- Egypt (Arabic, the modern regional language) ----
    "ptahhotep.humility": "كن متواضعًا وأصغِ؛ فالكلام الحسن أندر من الزمرد، ومع ذلك يوجد حتى عند الجواري.",
    "ptahhotep.maat": "اعمل بالماعت (الحق والعدل) ما دمت حيًّا؛ فهي تبقى، والظلم لا يبلغ مرساه بأمان.",
    "amenemope.silent": "الرجل الصامت المتحكم بنفسه خير من الغني الحاد اللسان.",
    "akhenaten.aten": "آتون، قرص الشمس الحي الأوحد، هو الخالق الواحد لكل أرضٍ ولكل حي.",
    "dispute.death": "حين يثقل الحزن الحياة، يقف الموت أمامي كعطر المُرّ، كالشفاء من مرض.",
    "bookdead.heart": "بعد الموت يُوزن القلب أمام ريشة الماعت؛ والصالحون ينالون الحياة الأبدية.",
    # ---- Mesopotamia (Arabic, the modern regional language) ----
    "shuruppak.prudence": "لا تسرق، لا تكذب، لا تطمع؛ فالتعامل الصادق المعتدل يُنمّي الحياة.",
    "gilgamesh.mortality": "الحياة الأبدية محفوظة للآلهة؛ فاغتنم ما لديك من حياةٍ وطعامٍ ورفاق، فلا بدّ لك أن تموت.",
    "theodicy.suffering": "حتى الصالحون يُصابون بمعاناةٍ لا تُفسَّر؛ وعقول الآلهة بعيدة المنال.",
    "dialogue.futility": "كل غرضٍ يمكن تأييده ثم دحضه؛ فربما لا خطة بشرية تهمّ في النهاية.",
    "hammurabi.talion": "شُرّع القانون كي لا يظلم القويُّ الضعيف — العين بالعين.",
    "enuma.order": "النظام (مردوخ) يُصاغ من الفوضى البدئية (تيامات)؛ فالكون يُصنع من الصراع.",
}

# Year of birth for persons (BCE); for anonymous texts, approximate composition/era date.
BIRTH = {
    # Greece
    "Thales": "c. 624 BCE", "Anaximander": "c. 610 BCE", "Anaximenes": "c. 586 BCE",
    "Pythagoras": "c. 570 BCE", "Xenophanes": "c. 570 BCE", "Heraclitus": "c. 535 BCE",
    "Parmenides": "c. 515 BCE", "Zeno of Elea": "c. 490 BCE", "Empedocles": "c. 494 BCE",
    "Anaxagoras": "c. 500 BCE", "Democritus": "c. 460 BCE", "Protagoras": "c. 490 BCE",
    "Gorgias": "c. 483 BCE", "Socrates": "470 BCE", "Plato": "c. 428 BCE",
    "Aristotle": "384 BCE", "Diogenes": "c. 412 BCE", "Epicurus": "341 BCE",
    "Zeno of Citium": "c. 334 BCE",
    # China
    "Confucius": "551 BCE", "Mencius": "c. 372 BCE", "Xunzi": "c. 310 BCE",
    "Laozi": "c. 571 BCE", "Zhuangzi": "c. 369 BCE", "Mozi": "c. 470 BCE",
    "Shang Yang": "c. 390 BCE", "Han Feizi": "c. 280 BCE", "Sun Tzu": "c. 544 BCE",
    "Gongsun Long": "c. 320 BCE",
    # India
    "Vedas": "c. 1500 BCE", "Upanishads": "c. 800 BCE", "Mahavira": "c. 599 BCE",
    "Buddha": "c. 563 BCE", "Makkhali Gosala": "c. 500 BCE", "Carvaka": "c. 600 BCE",
    "Kapila": "c. 550 BCE", "Panini": "c. 500 BCE",
    # Persia
    "Zoroaster": "c. 1000 BCE",
    # Israel (texts)
    "Proverbs": "c. 600 BCE", "Ecclesiastes": "c. 300 BCE", "Job": "c. 500 BCE",
    "Torah": "c. 600 BCE", "Prophets": "c. 750 BCE",
    # Egypt
    "Ptahhotep": "c. 2400 BCE", "Amenemope": "c. 1300 BCE", "Akhenaten": "c. 1353 BCE",
    "Dispute with the Ba": "c. 1900 BCE", "Book of the Dead": "c. 1550 BCE",
    # Mesopotamia
    "Instructions of Shuruppak": "c. 2600 BCE", "Epic of Gilgamesh": "c. 2100 BCE",
    "Babylonian Theodicy": "c. 1000 BCE", "Dialogue of Pessimism": "c. 1000 BCE",
    "Hammurabi": "c. 1810 BCE", "Enuma Elish": "c. 1200 BCE",
}
